In [ ]:
pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
# CREATING ARRAYS
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array((1,2,3))
arr3 = np.array(1)
arr4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr5 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr6 = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr4.ndim)
print(arr6.ndim)

print(np.arange(1,10))
print(np.linspace(1,10,9))
print(np.zeros((2,2)))
print(np.ones((2,2)))

In [ ]:
# ARRAY INDEXING
print(arr[1])
print(arr[-1])
print(arr5[-1,-1,-1])
print(arr2[1:])
print(arr6[-3:])
print(arr[0:7:2])
print(arr[1::3])
print(arr[::2])
print(arr4[1:3, 2:4])

In [ ]:
# Data Types Python and Numpy
"""
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
"""
array_tipo_float = np.array([1.2,2.5,3])
array_tipo_string = np.array([1.2,2.5,3], dtype='S2')
print(array_tipo_float.dtype)
print(array_tipo_string.dtype)
#array_tipo_strin[1]+3
array_tipo_float[1] + 3

array_int = np.array([0,2,3,4,-1])
array_str = array_int.astype('S')
array_bool = array_int.astype(bool)
print(array_int.dtype)
print(array_str.dtype)
print(array_bool.dtype)
print(array_bool)

In [ ]:
# Copy vs View
"""
Copy creates a new array while View shows an array that can modify the original array
"""
arr10 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
copy_array = arr10.copy()
copy_array[2] = 10
print(copy_array)

copy_array = arr10.copy()
view_array = arr10.view()
print(copy_array.base)
print(view_array.base)

In [ ]:
# SHAPE

arr_shape = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_shape)
print(arr_shape.shape)
arr_shape2 = np.array([1,2,3,4], ndmin=5)
print(arr_shape2.shape)

# RESHAPE

array_res = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array_resh = array_res.reshape(3,4)
print(array_resh)
array_resh2 = array_res.reshape(2,2,3)
print(array_resh2)

print(array_resh.base)
(array_resh[2,2]) = 0
print(array_resh.base)
print(array_resh) # This demonstrates that reshape is a view

array_res2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array_res2.reshape(3,-1)) # -1 is used when the value of a dimension is unknown

array_res3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(array_res3.reshape(-1))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
(1, 1, 1, 1, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10  0 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Array Iterating

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y, end=" ")
    print('\n')


arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr2:
    for y in x:
        for z in y:
            print(z, end=" ")
print('\n')


arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr3):
    print(x, end=' ')


arr4 = np.array([1,2,3,4,5])
for x in np.nditer(arr4, flags=['buffered'], op_dtypes=['S']):
    print(x)
print(arr4)


arr5 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr5[:, ::2]):
    print(x)
for idx,x in np.ndenumerate(arr5):
    print(idx, x)

In [ ]:
# Join Arrays

arr_j1 = np.array([1,2,3,4])
arr_j2 = np.array([5,6,7,8])
arr_j12 = np.concatenate((arr_j1, arr_j2))
print(arr_j12)

arr_j3 = np.array([[1,2,3],[4,5,6]])
arr_j4 = np.array([[7,8,9],[10,11,12]])
arr_j34_2 = np.concatenate((arr_j3, arr_j4), axis=0)
arr_j34_1 = np.concatenate((arr_j3, arr_j4), axis=1)
print(arr_j34_2)
print(arr_j34_1)

arr_jst34 = np.stack((arr_j3, arr_j4), axis=1)
print(arr_jst34)

arr_hstack12 = np.hstack((arr_j1, arr_j2)) # Stacking Along Rows
print(arr_hstack12)
arr_vstack12 = np.vstack((arr_j1, arr_j2)) # Stacking Along Columns
print(arr_vstack12)
arr_dstack12 = np.dstack((arr_j1, arr_j2)) # Stacking Along Height (Depth)
print(arr_dstack12)

In [ ]:
# Splitting Arrays

arr_j1 = np.array([1,2,3,4,5,6,7,8,9])
arr_j1_sp = np.array_split(arr_j1, 3)
print(arr_j1_sp)
print(arr_j1_sp[1])

arr_j2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
arr_j3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
arr_j2_sp = np.array_split(arr_j2, 3)
arr_j3_sp = np.array_split(arr_j3, 3)
arr_j3_sp_1 = np.array_split(arr_j3, 3, axis=1)
print(arr_j2_sp)
print(arr_j3_sp)
print(arr_j3_sp_1)
# vsplit, dsplit, hsplit work similar than stack

In [ ]:
# Search elements in arrays

arr_se = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np.where(arr_se == 5 ))
print(np.where(arr_se%2 == 0 ))

arr_se_2 = np.array([6, 7, 8, 9])
print( np.searchsorted(arr_se_2, 8) )
print( np.searchsorted(arr_se_2, 8, side='right') )
print( np.searchsorted(arr_se_2, [6,8]) )

In [ ]:
# Sorting Arrays

arr_s1 = np.array([3, 2, 0, 1])
arr_s2 = np.array(['banana', 'cherry', 'apple'])
arr_s3 = np.array([True, False, True])
arr_s4 = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr_s1))
print(np.sort(arr_s2))
print(np.sort(arr_s3))
print(np.sort(arr_s4))

In [ ]:
# Filter Array

arr_fil1 = np.array([41, 42, 43, 44])
x = [True, False, True, False]
print(arr_fil1[x])

arr_fil2 = np.array([3,4,5,6,7,8,9,10])
filter = []
for i in arr_fil2:
    if i>8: filter.append(True)
    else: filter.append(False)
print(filter)
print(arr_fil2[filter])

filter_2 = arr_fil2>8  # Creating Filter Directly From Array
print(filter_2)
print(arr_fil2[filter_2])

In [ ]:
from numpy import random

In [ ]:
# Generate random Numbers

print( random.rand() )
print( random.rand(4) )
print( random.rand(2,2) )

print( random.randint(5) )
print( random.randint(100, size=5) )
print( random.randint(100, size=(2,3)) )

print( random.choice( [1,2,3] ) )
print( random.choice( [1,2,3], size=(2,3) ) )

In [ ]:
# Random Data Distribution

print( random.choice( [1,2,3,4], p=[0.1,0.8,0.1,0], size=(3) ) )
print( random.choice( [1,2,3,4], p=[0.1,0.8,0.1,0], size=(3,3) ) )

# Random Permutations

arr_per1 = np.array([1, 2, 3, 4, 5])
random.shuffle(arr_per1)
print(arr_per1)

arr_per2 = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr_per2))

In [ ]:
pip install seaborn

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
sns.distplot([0, 1, 2, 3, 4, 5])
plt.show()

In [ ]:
x_norm1 = random.normal(size=(2, 3))
x_norm2 = random.normal(loc=1, scale=2, size=(2, 3))
print(x_norm1)
print(x_norm2)
sns.distplot(random.normal(size=1000), hist=False)
plt.show()

In [ ]:
x_bino = random.binomial(n=10, p=0.5, size=10)
sns.distplot(random.binomial(n=100, p=0.5,size=1000), hist=False)

In [ ]:
x_poisson = random.poisson(lam=2, size=10)
print(x_poisson)
sns.distplot(random.poisson(lam=2, size=1000), kde=False)
plt.show()

In [ ]:
x_unif = random.uniform(size=(2, 3))
print(x_unif)

sns.distplot( random.uniform(low=10, high=100, size=1000), kde=True)
plt.show()

In [ ]:
x_log = random.logistic(loc=1, scale=2, size=(2, 3))
print(x_log)
sns.distplot( random.logistic(loc=1, scale=2, size=1000), kde=True )
plt.show()

In [ ]:
x_mult = random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
print(x_mult)

x_mult2 = random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6], size=10)
print(x_mult2)

In [ ]:
x_exp = random.exponential(scale=2, size=(2, 3))
print(x_exp)
sns.displot(random.exponential(scale=2, size=1000))
plt.show()

In [ ]:
x_chi = random.chisquare(df=2, size=(2, 3))
print(x_chi)
sns.distplot(random.chisquare(df=2, size=1000), hist=True)
plt.show()

In [ ]:
x_ray = random.rayleigh(scale=2, size=(2, 3))
print(x_ray)
sns.distplot( random.rayleigh(scale=1, size=1000), hist=True)
plt.show()

In [ ]:
x_par = random.pareto(a=2, size=(2, 3))
print(x_par)
sns.distplot( random.pareto(a=2, size=1000), hist=True )

In [ ]:
x_zip = random.zipf(a=2, size=(2, 3))
print(x_zip)
x_zip2 = random.zipf(a=2, size=1000)
sns.distplot( x_zip2[x_zip2<10], hist=True )
plt.show()

In [ ]:
# NUMPY UFUNC

def sum(x,y):
    return x+y
mysum = np.frompyfunc(sum,2,1)
print( mysum([1,2,3,4],[5,6,7,8]) )
print(type(np.sum))

[6 8 10 12]
<class 'numpy._ArrayFunctionDispatcher'>


In [ ]:
# Arithmetic functions

arr1 = [1,2,3,4,5,6]
arr2 = [2,3,4,5,6,7]
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))
print(np.power(arr1,arr2))
print(np.mod(arr1, arr2))
print(np.remainder(arr1,arr2))
print(np.divmod(arr1,arr2))
print(np.absolute(arr1))

[ 3  5  7  9 11 13]
[-1 -1 -1 -1 -1 -1]
[ 2  6 12 20 30 42]
[0.5        0.66666667 0.75       0.8        0.83333333 0.85714286]
[     1      8     81   1024  15625 279936]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
(array([0, 0, 0, 0, 0, 0]), array([1, 2, 3, 4, 5, 6]))
[1 2 3 4 5 6]


In [ ]:
# Round decimals

print( np.trunc([3.234]) )
print( np.fix([3.234, -2.845]) )
print( np.around(3.2524, 1) )
print( np.floor(3.6524) ) # %ounds off decimal to nearest lower integer.
print( np.ceil(3.6524) ) # %ounds off decimal to nearest upper integer.

# Numpy Logs

arr_lo = np.arange( 1,10 )
print( np.log2(arr_lo) )
print( np.log(arr_lo) )
print( np.log10(arr_lo) )
print( np.log2(arr_lo) )

import math
loga = np.frompyfunc( math.log,2,1 )
print( loga( 32, 2 ))

[3.]
[ 3. -2.]
3.3
3.0
4.0


In [ ]:
# NumPy Summations

arr_sum1 = np.array([1,2,3,4])
arr_sum2 = np.array([5,6,7,8])
print( np.add(arr_sum1, arr_sum2) )
print( np.sum([arr_sum1, arr_sum2]) )
print( np.sum([arr_sum1, arr_sum2], axis=1) )
print( np.cumsum( arr_sum1 ) )

# Numpy Products

arr_pro1 = np.array([1,2,3,4])
arr_pro2 = np.array([5,6,7,8])
print(np.prod(arr_pro1))
print(np.prod([arr_pro1, arr_pro2]) )
print(np.prod([arr_pro1, arr_pro2], axis=0) )
print(np.prod([arr_pro1, arr_pro2], axis=1) )
print(np.cumprod([arr_pro1, arr_pro2]) )

# Numpy differences

arr_diff = np.array( [3,6,9,20,10] )
print( np.diff(arr_diff) )
print( np.diff(arr_diff, n=2) )
print( np.diff(arr_diff, n=3) )
print( np.diff(arr_diff, n=4) )

[ 6  8 10 12]
36
[10 26]
[ 1  3  6 10]
24
40320
[ 5 12 21 32]
[  24 1680]
[    1     2     6    24   120   720  5040 40320]
[  3   3  11 -10]
[  0   8 -21]
[  8 -29]
[-37]


In [ ]:
# Lowest Common Multiple

arr_lcm = np.array( [8, 10] )
arr_lcm2 = np.arange(1,4)

print( np.lcm( 8, 10) )
print( np.lcm.reduce(arr_lcm2) )

# Greates Common Denominator

arr_gcd = np.array( [8,10] )
arr_gcd2 = np.arange( 1,4 )

print( np.gcd(8,10) )
print( np.gcd.reduce( arr_gcd2) )

# Comparison functions

array_co1 = np.array([1,2,3])
array_co2 = np.array([2,2,2])
print(np.equal(array_co1, array_co2))
print(np.not_equal(array_co1, array_co2))
print(np.greater(array_co1, array_co2))
print(np.greater_equal(array_co1, array_co2))
print(np.less(array_co1, array_co2))
print(np.less_equal(array_co1, array_co2))

40
6
2
1
[False  True False]
[ True False  True]
[False False  True]
[False  True  True]
[ True False False]
[ True  True False]


In [ ]:
# Numpy Trigonometrics Functions

# Sin, Cos y Tan
arr_sin = np.array( [ np.pi/2, np.pi/3, np.pi/4, np.pi/5 ] )
print( np.sin(np.pi/2) )
print( np.sin(arr_sin) )

# Convert Degree to Radians and viceverse

arr_deg = np.array( [90, 180, 270, 360] )
print( np.deg2rad(arr_deg) )
arr_rad = np.array( [ np.pi/2, np.pi, 1.5*np.pi, 2*np.pi ] )
print( np.rad2deg(arr_rad) )

# Arcsin, Arccos, Arctan

arr_ang = np.array( [1, 0, -1] )
print( np.arcsin(1) )
print( np.arcsin(arr_ang) )

# Hypotenues

print( np.hypot(3,4) )

# The same with sinh, cosh, tanh, arcsinh, arccosh, arctanh

1.0
[1.         0.8660254  0.70710678 0.58778525]
[1.57079633 3.14159265 4.71238898 6.28318531]
[ 90. 180. 270. 360.]
1.5707963267948966
[ 1.57079633  0.         -1.57079633]
5.0


In [ ]:
# Set Operations

arr_set1 = np.array( [1,2,3,1,2,6,1,5] )
arr_set2 = np.array( [2,5,6,8,9] )

print(np.unique(arr_set1))
print(np.union1d(arr_set1, arr_set2))
print(np.intersect1d(arr_set1, arr_set2, assume_unique=True))
print(np.setdiff1d(arr_set1, arr_set2, assume_unique=True))
print(np.setxor1d(arr_set1, arr_set2, assume_unique=True))

In [ ]:
# READ FILES

insurance_csv = np.genfromtxt( 'insurance.csv', dtype=None, delimiter=',', skip_header=0, encoding=None )
# insurance_csv_2 = [row[-np.isnan[row]] for row in insurance_csv]                Only value numerics

import pandas as pd

copia = pd.DataFrame(insurance_csv)
copia2 = copia.apply(pd.to_numeric, errors='coerce')
copia3 = copia2.drop([1,4,5], axis=1)
copia4 = copia3.drop(0, axis=0)
print(copia4)

# insurance_csv2 = [ i[-np.isnan(i)] for i in insurance_csv_on ]

         0       2    3            6
1     19.0  27.900  0.0  16884.92400
2     18.0  33.770  1.0   1725.55230
3     28.0  33.000  3.0   4449.46200
4     33.0  22.705  0.0  21984.47061
5     32.0  28.880  0.0   3866.85520
...    ...     ...  ...          ...
1334  50.0  30.970  3.0  10600.54830
1335  18.0  31.920  0.0   2205.98080
1336  18.0  36.850  0.0   1629.83350
1337  21.0  25.800  0.0   2007.94500
1338  61.0  29.070  0.0  29141.36030

[1338 rows x 4 columns]


In [ ]:
# Stadistics Functions

print(np.std( [3,3,4,5,6] ))
print(np.var( [3,3,4,5,6] ))

array= np.arange( 1,101 )
for i in range(1,5):
    print(np.percentile( array, i, axis=0 ))

np.corrcoef( copia4[0 ], copia4[2] )

# Regression Lineal
print(type(copia[0][1]))

age_mean = np.mean(copia4[0])
bmi_mean = np.mean(copia4[2])

numerator = np.sum((copia4[0] - age_mean) * (copia4[2] - bmi_mean))
denominator = np.sum( np.square( copia4[0]-age_mean ) )
m = numerator/denominator
print(m)
# y = mx +b

b = bmi_mean - m * ( age_mean )
print(b)

arr_rl = copia4[0]*m + b
print(arr_rl - copia4[2])

1.16619037896906
1.3599999999999999
1.99
2.98
3.9699999999999998
4.96
<class 'str'>
0.04742791722456038
28.8038893051695
1       1.805020
2      -4.112408
3      -2.868129
4       7.664011
5       1.441583
          ...   
1334    0.205285
1335   -2.262408
1336   -7.192408
1337    3.999876
1338    2.626992
Length: 1338, dtype: float64


In [ ]:
# Linear Algebra

array_la1 = np.array( [[2,3], [4,3]] )
array_la2 = np.array( [[1,2], [3,2]] )
array_la3 = np.array( [[[1,2], [3,2]], [[4,5],[1,3]]] )

print( array_la1 )
print( array_la2 )

print( np.dot(array_la1, array_la2) )
print( np.linalg.multi_dot( [array_la1, array_la2] ) )

print( np.inner( array_la1, array_la2 ) )

print( np.tensordot( array_la3, array_la2 ) )

print( np.einsum( 'ij,ij->ij ', array_la1, array_la2 ) )

print( np.linalg.matrix_power( array_la1, 2 ) )

print( np.kron( array_la1, array_la2 ) )

print( np.linalg.eig( array_la1 ) )
print( np.linalg.eigvals( array_la1 ) )

print( np.linalg.inv( array_la1 ) )

print( np.linalg.cond( array_la1 ) )

print( np.linalg.det( array_la1 ) )

print( np.dot( array_la1, np.linalg.inv(array_la1) ) )

array_la4 = np.array( [[1,4],[6,18]] )
array_la5 = np.array( [10, 42] )
print( np.linalg.solve(array_la4, array_la5) )

print( np.eye(2,2, dtype=int) )

[[2 3]
 [4 3]]
[[1 2]
 [3 2]]
[[11 10]
 [13 14]]
[[11 10]
 [13 14]]
[[ 8 12]
 [10 18]]
[18 23]
[[ 2  6]
 [12  6]]
[[16 15]
 [20 21]]
[[ 2  4  3  6]
 [ 6  4  9  6]
 [ 4  8  3  6]
 [12  8  9  6]]
EigResult(eigenvalues=array([-1.,  6.]), eigenvectors=array([[-0.70710678, -0.6       ],
       [ 0.70710678, -0.8       ]]))
[-1.  6.]
[[-0.5         0.5       ]
 [ 0.66666667 -0.33333333]]
6.1712927295533255
-6.0
[[ 1.00000000e+00  5.55111512e-17]
 [-1.11022302e-16  1.00000000e+00]]
[-2.  3.]
[[1 0]
 [0 1]]


In [ ]:
# Saving Objects

array_so1 = np.array( [1,2,3] )
np.save( 'aea', array_so1 )
array_so11 = np.load( 'aea.npy' )
print(array_so11)

np.savetxt( 'aaa.csv', array_so1 )
array_so2 = np.loadtxt( 'aaa.csv' )
print(array_so2)

[1 2 3]
[1. 2. 3.]
